
name: OnWindows

# When the workflow will run
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  # Job 'runtests', based on https://stackoverflow.com/questions/61558780/python-testing-with-github-actions-on-windows
  runtests:
    runs-on: windows-2019
    steps:
      # Check out the repository
      #- uses: actions/checkout@v2
      - uses: actions/checkout@v1

      # Install Python
      - uses: actions/setup-python@v1
        with:
          python-version: '3.6'

      - name: Download MonetDB
        run: |
          python download-monetdb.py $Env:RUNNER_TEMP\monetdb.msi
          dir $Env:RUNNER_TEMP

      - name: Install MonetDB
        run: |
          msiexec /i $Env:RUNNER_TEMP\monetdb.msi /norestart /qn /log $Env:RUNNER_TEMP\install.txt
          type $Env:RUNNER_TEMP\install.txt
          dir "c:\Program Files"
          dir "c:\Program Files\MonetDB"
          dir "c:\Program Files\MonetDB\MonetDB5"

      # - name: run the test
      #   run: |
      #     python -m venv venv
      #     venv\Scripts\Activate.ps1
      #     python -m pip install -r requirements.txt
      #     python test.py
