
name: OnWindows

# When the workflow will run
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  # Job 'runtests', based on https://stackoverflow.com/questions/61558780/python-testing-with-github-actions-on-windows
  runtests:
    runs-on: windows-2019
    steps:
      # Check out the repository
      #- uses: actions/checkout@v2
      - uses: actions/checkout@v1

      # Install Python
      - uses: actions/setup-python@v1
        with:
          python-version: '3.6'

      - name: Download MonetDB
        run: |
          python download-monetdb.py ${{ runner.temp }}\monetdb.msi
          dir ${{ runner.temp }}
          7z x ${{ runner.temp }}\monetdb.msi -o${{ runner.temp }}\staging
          dir ${{ runner.temp }}\staging

#          icacls ${{ runner.temp }} /t /grant Users:F /T
      - name: Install MonetDB
        run: |
          python install-monetdb.py ${{ runner.temp }}\staging ${{ runner.temp }}\MONET
          dir ${{ runner.temp }}\MONET
          dir ${{ runner.temp }}\MONET\bin
          ${{ runner.temp }}\MONET\bin\mserver5.exe --help

      # - name: run the test
      #   run: |
      #     python -m venv venv
      #     venv\Scripts\Activate.ps1
      #     python -m pip install -r requirements.txt
      #     python test.py
